#
# This test suite is intended to verify the correct behaviour of actions affecting
# or being afected by the numberic part of the version (MAJOR.MINOR.PATCH) and/or
# the volatile build metadata.
#
# This module can be used to test the common functionality of Makefile.semver-basic
# and Makefile.semver-complete
#

runtests:

	$(DO) title TEXT="$(firstword $(MAKEFILE_LIST))"

	$(DO) header TEXT="Checking unit tests IO"
	$(DO) setup VALUE="IO data" verify EXPECTED="IO data"
	$(DO) setup VALUE="" verify EXPECTED=""

	$(DO) header TEXT="Default empty version"
	$(DO) setup VALUE="" capture ACTION="version.print" verify EXPECTED="0.0.0"

	$(DO) header TEXT="Print version without metadata set"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.print" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="0.0.0" capture ACTION="version.print" verify EXPECTED="0.0.0"

	$(DO) header TEXT="Print version with metadata set"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:7564" capture ACTION="version.print" verify EXPECTED="3.14.15+git:7564"
	$(DO) setup VALUE="0.0.0" VERSION_METADATA="git:7564" capture ACTION="version.print" verify EXPECTED="0.0.0+git:7564"

	$(DO) header TEXT="version.init writes zero version when no data present"
	$(DO) setup VALUE="" execute ACTION="version.init" verify EXPECTED="0.0.0"

	$(DO) header TEXT="version.init keeps existing data"
	$(DO) setup VALUE="3.14.15" execute ACTION="version.init" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="100000.100000.100000" execute ACTION="version.init" verify EXPECTED="100000.100000.100000"

	$(DO) header TEXT="Incrementing patch versions with version.nextpatch"
	$(DO) setup VALUE=""
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.1"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.2"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.3"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.4"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.5"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.6"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.7"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.8"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.9"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.10"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.11"
	$(DO) setup VALUE="0.0.19" execute ACTION="version.nextpatch" verify EXPECTED="0.0.20"
	$(DO) setup VALUE="0.0.99" execute ACTION="version.nextpatch" verify EXPECTED="0.0.100"
	$(DO) setup VALUE="0.0.999" execute ACTION="version.nextpatch" verify EXPECTED="0.0.1000"
	$(DO) setup VALUE="0.0.9999" execute ACTION="version.nextpatch" verify EXPECTED="0.0.10000"
	$(DO) setup VALUE="0.0.99999" execute ACTION="version.nextpatch" verify EXPECTED="0.0.100000"
	$(DO) setup VALUE="0.0.100000" execute ACTION="version.nextpatch" verify EXPECTED="0.0.100001"

	$(DO) header TEXT="Incrementing patch versions with version.next"
	$(DO) setup VALUE=""
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.1"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.2"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.3"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.4"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.5"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.6"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.7"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.8"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.9"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.10"
	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.11"
	$(DO) setup VALUE="0.0.19" execute ACTION="version.next" verify EXPECTED="0.0.20"
	$(DO) setup VALUE="0.0.99" execute ACTION="version.next" verify EXPECTED="0.0.100"
	$(DO) setup VALUE="0.0.999" execute ACTION="version.next" verify EXPECTED="0.0.1000"
	$(DO) setup VALUE="0.0.9999" execute ACTION="version.next" verify EXPECTED="0.0.10000"
	$(DO) setup VALUE="0.0.99999" execute ACTION="version.next" verify EXPECTED="0.0.100000"
	$(DO) setup VALUE="0.0.100000" execute ACTION="version.next" verify EXPECTED="0.0.100001"

	$(DO) header TEXT="Incrementing minor versions"
	$(DO) setup VALUE=""
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.1.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.2.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.3.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.4.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.5.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.6.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.7.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.8.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.9.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.10.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.11.0"
	$(DO) setup VALUE="0.19.0" execute ACTION="version.nextminor" verify EXPECTED="0.20.0"
	$(DO) setup VALUE="0.99.0" execute ACTION="version.nextminor" verify EXPECTED="0.100.0"
	$(DO) setup VALUE="0.999.0" execute ACTION="version.nextminor" verify EXPECTED="0.1000.0"
	$(DO) setup VALUE="0.9999.0" execute ACTION="version.nextminor" verify EXPECTED="0.10000.0"
	$(DO) setup VALUE="0.99999.0" execute ACTION="version.nextminor" verify EXPECTED="0.100000.0"
	$(DO) setup VALUE="0.100000.0" execute ACTION="version.nextminor" verify EXPECTED="0.100001.0"

	$(DO) header TEXT="Incrementing major versions"
	$(DO) setup VALUE=""
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="1.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="2.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="3.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="4.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="5.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="6.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="7.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="8.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="9.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="10.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="11.0.0"
	$(DO) setup VALUE="19.0.0" execute ACTION="version.nextmajor" verify EXPECTED="20.0.0"
	$(DO) setup VALUE="99.0.0" execute ACTION="version.nextmajor" verify EXPECTED="100.0.0"
	$(DO) setup VALUE="999.0.0" execute ACTION="version.nextmajor" verify EXPECTED="1000.0.0"
	$(DO) setup VALUE="9999.0.0" execute ACTION="version.nextmajor" verify EXPECTED="10000.0.0"
	$(DO) setup VALUE="99999.0.0" execute ACTION="version.nextmajor" verify EXPECTED="100000.0.0"
	$(DO) setup VALUE="100000.0.0" execute ACTION="version.nextmajor" verify EXPECTED="100001.0.0"

	$(DO) header TEXT="Keeping major and minor during patch increment"
	$(DO) setup VALUE="15.42.0"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="15.42.1"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="15.42.2"
	$(DO) setup VALUE="2.13.60"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="2.13.61"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="2.13.62"
	$(DO) setup VALUE="3.14.999"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="3.14.1000"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="3.14.1001"
	$(DO) setup VALUE="15.42.0"
	$(DO) execute ACTION="version.next" verify EXPECTED="15.42.1"
	$(DO) execute ACTION="version.next" verify EXPECTED="15.42.2"
	$(DO) setup VALUE="2.13.60"
	$(DO) execute ACTION="version.next" verify EXPECTED="2.13.61"
	$(DO) execute ACTION="version.next" verify EXPECTED="2.13.62"
	$(DO) setup VALUE="3.14.999"
	$(DO) execute ACTION="version.next" verify EXPECTED="3.14.1000"
	$(DO) execute ACTION="version.next" verify EXPECTED="3.14.1001"

	$(DO) header TEXT="Keeping major and reseting patch during minor increment"
	$(DO) setup VALUE="15.42.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="15.43.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="15.44.0"
	$(DO) setup VALUE="2.99.35"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="2.100.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="2.101.0"
	$(DO) setup VALUE="876.144.84754"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="876.145.0"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="876.146.0"

	$(DO) header TEXT="Reseting minor and patch during major increment"
	$(DO) setup VALUE="15.42.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="16.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="17.0.0"
	$(DO) setup VALUE="2.99.35"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="3.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="4.0.0"
	$(DO) setup VALUE="876.144.84754"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="877.0.0"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="878.0.0"

	$(DO) header TEXT="incrementing major, minor or patch with non persistent metadata=git:CAFEBABE"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" verify EXPECTED="3.14.15"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.14.15+git:CAFEBABE"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.nextpatch" verify EXPECTED="3.14.16"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.14.16+git:CAFEBABE"
	$(DO) setup VALUE="3.14.16" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.next" verify EXPECTED="3.14.17"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.14.17+git:CAFEBABE"
	$(DO) setup VALUE="3.14.17" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.nextminor" verify EXPECTED="3.15.0"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.15.0+git:CAFEBABE"
	$(DO) setup VALUE="3.15.42" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.nextmajor" verify EXPECTED="4.0.0"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="4.0.0+git:CAFEBABE"

	$(DO) header TEXT="testing output variables without non persistent metadata"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_DATA" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_NUMBER" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_MAJOR" verify EXPECTED="3"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_MINOR" verify EXPECTED="14"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_PATCH" verify EXPECTED="15"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_METADATA" verify EXPECTED=""

	$(DO) header TEXT="testing output variables with non persistent metadata=git:CAFEBABE"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION" verify EXPECTED="3.14.15+git:CAFEBABE"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_DATA" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_NUMBER" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_MAJOR" verify EXPECTED="3"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_MINOR" verify EXPECTED="14"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_PATCH" verify EXPECTED="15"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_METADATA" verify EXPECTED="git:CAFEBABE"
