#
# This test suite is intended to verify the correct behaviour of actions affecting
# or being afected by the release cycles and optionally the build metadata.
#


runtests:

	$(DO) title TEXT="$(firstword $(MAKEFILE_LIST))"

	$(DO) header TEXT="Checking unit tests IO"
	$(DO) setup VALUE="IO data" verify EXPECTED="IO data"
	$(DO) setup VALUE="" verify EXPECTED=""

	$(DO) header TEXT="Print version without metadata set"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.print" verify EXPECTED="3.14.15-beta.42"
	$(DO) setup VALUE="0.0.0-beta.42" capture ACTION="version.print" verify EXPECTED="0.0.0-beta.42"

	$(DO) header TEXT="Print version with metadata set"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:7564" capture ACTION="version.print" verify EXPECTED="3.14.15-beta.42+git:7564"
	$(DO) setup VALUE="0.0.0-beta.42" VERSION_METADATA="git:7564" capture ACTION="version.print" verify EXPECTED="0.0.0-beta.42+git:7564"

	$(DO) header TEXT="just running make keeps existing data"
	$(DO) setup VALUE="3.14.15-beta.42"
	$(DO) callmake verify EXPECTED="3.14.15-beta.42"
	$(DO) setup VALUE="100000.100000.100000-beta.42"
	$(DO) callmake verify EXPECTED="100000.100000.100000-beta.42"

	$(DO) header TEXT="Incrementing patch versions with version.nextpatch"
	$(DO) setup VALUE="0.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.1-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.2-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.3-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.4-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.5-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.6-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.7-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.8-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.9-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.10-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="0.0.11-alphabase.99"
	$(DO) setup VALUE="0.0.19-alphabase.99" execute ACTION="version.nextpatch" verify EXPECTED="0.0.20-alphabase.99"
	$(DO) setup VALUE="0.0.99-alphabase.99" execute ACTION="version.nextpatch" verify EXPECTED="0.0.100-alphabase.99"
	$(DO) setup VALUE="0.0.999-alphabase.99" execute ACTION="version.nextpatch" verify EXPECTED="0.0.1000-alphabase.99"
	$(DO) setup VALUE="0.0.9999-alphabase.99" execute ACTION="version.nextpatch" verify EXPECTED="0.0.10000-alphabase.99"
	$(DO) setup VALUE="0.0.99999-alphabase.99" execute ACTION="version.nextpatch" verify EXPECTED="0.0.100000-alphabase.99"
	$(DO) setup VALUE="0.0.100000-alphabase.99" execute ACTION="version.nextpatch" verify EXPECTED="0.0.100001-alphabase.99"

#	$(DO) header TEXT="Incrementing patch versions with version.next"
#	$(DO) setup VALUE="0.0.0-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.1-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.2-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.3-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.4-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.5-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.6-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.7-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.8-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.9-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.10-alphabase.99"
#	$(DO) execute ACTION="version.next" verify EXPECTED="0.0.11-alphabase.99"
#	$(DO) setup VALUE="0.0.19-alphabase.99" execute ACTION="version.next" verify EXPECTED="0.0.20-alphabase.99"
#	$(DO) setup VALUE="0.0.99-alphabase.99" execute ACTION="version.next" verify EXPECTED="0.0.100-alphabase.99"
#	$(DO) setup VALUE="0.0.999-alphabase.99" execute ACTION="version.next" verify EXPECTED="0.0.1000-alphabase.99"
#	$(DO) setup VALUE="0.0.9999-alphabase.99" execute ACTION="version.next" verify EXPECTED="0.0.10000-alphabase.99"
#	$(DO) setup VALUE="0.0.99999-alphabase.99" execute ACTION="version.next" verify EXPECTED="0.0.100000-alphabase.99"
#	$(DO) setup VALUE="0.0.100000-alphabase.99" execute ACTION="version.next" verify EXPECTED="0.0.100001-alphabase.99"

	$(DO) header TEXT="Incrementing minor versions"
	$(DO) setup VALUE="0.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.1.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.2.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.3.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.4.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.5.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.6.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.7.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.8.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.9.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.10.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="0.11.0-alphabase.99"
	$(DO) setup VALUE="0.19.0-alphabase.99" execute ACTION="version.nextminor" verify EXPECTED="0.20.0-alphabase.99"
	$(DO) setup VALUE="0.99.0-alphabase.99" execute ACTION="version.nextminor" verify EXPECTED="0.100.0-alphabase.99"
	$(DO) setup VALUE="0.999.0-alphabase.99" execute ACTION="version.nextminor" verify EXPECTED="0.1000.0-alphabase.99"
	$(DO) setup VALUE="0.9999.0-alphabase.99" execute ACTION="version.nextminor" verify EXPECTED="0.10000.0-alphabase.99"
	$(DO) setup VALUE="0.99999.0-alphabase.99" execute ACTION="version.nextminor" verify EXPECTED="0.100000.0-alphabase.99"
	$(DO) setup VALUE="0.100000.0-alphabase.99" execute ACTION="version.nextminor" verify EXPECTED="0.100001.0-alphabase.99"

	$(DO) header TEXT="Incrementing major versions"
	$(DO) setup VALUE="0.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="1.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="2.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="3.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="4.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="5.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="6.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="7.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="8.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="9.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="10.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="11.0.0-alphabase.99"
	$(DO) setup VALUE="19.0.0-alphabase.99" execute ACTION="version.nextmajor" verify EXPECTED="20.0.0-alphabase.99"
	$(DO) setup VALUE="99.0.0-alphabase.99" execute ACTION="version.nextmajor" verify EXPECTED="100.0.0-alphabase.99"
	$(DO) setup VALUE="999.0.0-alphabase.99" execute ACTION="version.nextmajor" verify EXPECTED="1000.0.0-alphabase.99"
	$(DO) setup VALUE="9999.0.0-alphabase.99" execute ACTION="version.nextmajor" verify EXPECTED="10000.0.0-alphabase.99"
	$(DO) setup VALUE="99999.0.0-alphabase.99" execute ACTION="version.nextmajor" verify EXPECTED="100000.0.0-alphabase.99"
	$(DO) setup VALUE="100000.0.0-alphabase.99" execute ACTION="version.nextmajor" verify EXPECTED="100001.0.0-alphabase.99"

	$(DO) header TEXT="Keeping major and minor and cycle during patch increment"
	$(DO) setup VALUE="15.42.0-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="15.42.1-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="15.42.2-alphabase.99"
	$(DO) setup VALUE="2.13.60-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="2.13.61-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="2.13.62-alphabase.99"
	$(DO) setup VALUE="3.14.999-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="3.14.1000-alphabase.99"
	$(DO) execute ACTION="version.nextpatch" verify EXPECTED="3.14.1001-alphabase.99"
# 	$(DO) setup VALUE="15.42.0-alphabase.99"
# 	$(DO) execute ACTION="version.next" verify EXPECTED="15.42.1-alphabase.99"
# 	$(DO) execute ACTION="version.next" verify EXPECTED="15.42.2-alphabase.99"
# 	$(DO) setup VALUE="2.13.60-alphabase.99"
# 	$(DO) execute ACTION="version.next" verify EXPECTED="2.13.61-alphabase.99"
# 	$(DO) execute ACTION="version.next" verify EXPECTED="2.13.62-alphabase.99"
# 	$(DO) setup VALUE="3.14.999-alphabase.99"
# 	$(DO) execute ACTION="version.next" verify EXPECTED="3.14.1000-alphabase.99"
# 	$(DO) execute ACTION="version.next" verify EXPECTED="3.14.1001-alphabase.99"

	$(DO) header TEXT="Keeping major and cycle and reseting patch during minor increment"
	$(DO) setup VALUE="15.42.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="15.43.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="15.44.0-alphabase.99"
	$(DO) setup VALUE="2.99.35-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="2.100.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="2.101.0-alphabase.99"
	$(DO) setup VALUE="876.144.84754-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="876.145.0-alphabase.99"
	$(DO) execute ACTION="version.nextminor" verify EXPECTED="876.146.0-alphabase.99"

	$(DO) header TEXT="Keeping cylce and rseting minor and patch during major increment"
	$(DO) setup VALUE="15.42.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="16.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="17.0.0-alphabase.99"
	$(DO) setup VALUE="2.99.35-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="3.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="4.0.0-alphabase.99"
	$(DO) setup VALUE="876.144.84754-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="877.0.0-alphabase.99"
	$(DO) execute ACTION="version.nextmajor" verify EXPECTED="878.0.0-alphabase.99"

	$(DO) header TEXT="incrementing major, minor or patch with non persistent metadata=git:CAFEBABE"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" verify EXPECTED="3.14.15-beta.42"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.14.15-beta.42+git:CAFEBABE"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.nextpatch" verify EXPECTED="3.14.16-beta.42"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.14.16-beta.42+git:CAFEBABE"
# 	$(DO) setup VALUE="3.14.16-beta.42" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.next" verify EXPECTED="3.14.17-beta.42"
# 	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.14.17-beta.42+git:CAFEBABE"
	$(DO) setup VALUE="3.14.17-beta.42" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.nextminor" verify EXPECTED="3.15.0-beta.42"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="3.15.0-beta.42+git:CAFEBABE"
	$(DO) setup VALUE="3.15.42-beta.42" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.nextmajor" verify EXPECTED="4.0.0-beta.42"
	$(DO) capture VERSION_METADATA="git:CAFEBABE" ACTION="version.print" verify EXPECTED="4.0.0-beta.42+git:CAFEBABE"

	$(DO) header TEXT="testing output variables without non persistent metadata"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION" verify EXPECTED="3.14.15-beta.42"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_DATA" verify EXPECTED="3.14.15-beta.42"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_NUMBER" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_MAJOR" verify EXPECTED="3"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_MINOR" verify EXPECTED="14"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_PATCH" verify EXPECTED="15"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_METADATA" verify EXPECTED=""
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_CYCLE" verify EXPECTED="beta.42"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_CYCLE_NAME" verify EXPECTED="beta"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_CYCLE_STEP" verify EXPECTED="42"

	$(DO) header TEXT="testing output variables with non persistent metadata=git:CAFEBABE"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION" verify EXPECTED="3.14.15-beta.42+git:CAFEBABE"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_DATA" verify EXPECTED="3.14.15-beta.42"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_NUMBER" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_MAJOR" verify EXPECTED="3"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_MINOR" verify EXPECTED="14"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_PATCH" verify EXPECTED="15"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_METADATA" verify EXPECTED="git:CAFEBABE"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE" verify EXPECTED="beta.42"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE_NAME" verify EXPECTED="beta"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE_STEP" verify EXPECTED="42"

	$(DO) header TEXT="version cycle variables with empty pre release cycle data and empty metadata"
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_CYCLE" verify EXPECTED=""
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_CYCLE_NAME" verify EXPECTED=""
	$(DO) setup VALUE="3.14.15" capture ACTION="version.debug.VERSION_CYCLE_STEP" verify EXPECTED="1"

	$(DO) header TEXT="version cycle variables with empty pre release cycle data and metadata"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE" verify EXPECTED=""
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE_NAME" verify EXPECTED=""
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE_STEP" verify EXPECTED="1"

	$(DO) header TEXT="version cycle variables with defined pre release cycle data and empty metadata"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_CYCLE" verify EXPECTED="beta.42"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_CYCLE_NAME" verify EXPECTED="beta"
	$(DO) setup VALUE="3.14.15-beta.42" capture ACTION="version.debug.VERSION_CYCLE_STEP" verify EXPECTED="42"

	$(DO) header TEXT="version cycle variables with defined pre release cycle data and metadata"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE" verify EXPECTED="beta.42"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE_NAME" verify EXPECTED="beta"
	$(DO) setup VALUE="3.14.15-beta.42" VERSION_METADATA="git:CAFEBABE" capture ACTION="version.debug.VERSION_CYCLE_STEP" verify EXPECTED="42"

	$(DO) header TEXT="version.release without cycle data, with and without metadata"
	$(DO) setup VALUE="3.14.15" execute ACTION="version.release" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.release" verify EXPECTED="3.14.15"

	$(DO) header TEXT="version.release with cycle data, with and without metadata"
	$(DO) setup VALUE="3.14.15-alpha.42" execute ACTION="version.release" verify EXPECTED="3.14.15"
	$(DO) setup VALUE="3.14.15-alpha.42" VERSION_METADATA="git:CAFEBABE" execute ACTION="version.release" verify EXPECTED="3.14.15"

	$(DO) header TEXT="version.tocycle set from empty"
	$(DO) setup VALUE="" execute ACTION="version.tocycle.alphabase" verify EXPECTED="0.0.0-alphabase.1"
	$(DO) setup VALUE="3.14.15" execute ACTION="version.tocycle.betatest" verify EXPECTED="3.14.15-betatest.1"

	$(DO) header TEXT="version.tocycle step preservation/reset"
	$(DO) setup VALUE="3.14.15-alphabase.42" execute ACTION="version.tocycle.alphabase" verify EXPECTED="3.14.15-alphabase.42"
	$(DO) setup VALUE="3.14.15-alphabase.42" execute ACTION="version.tocycle.betatest" verify EXPECTED="3.14.15-betatest.1"

	$(DO) header TEXT="Incrementing cycle steps versions"
	$(DO) setup VALUE="1.2.3-betatest.1"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.2"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.3"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.4"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.5"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.6"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.7"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.8"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.9"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.10"
	$(DO) execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.11"
	$(DO) setup VALUE="1.2.3-betatest.19" execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.20"
	$(DO) setup VALUE="1.2.3-betatest.99" execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.100"
	$(DO) setup VALUE="1.2.3-betatest.999" execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.1000"
	$(DO) setup VALUE="1.2.3-betatest.9999" execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.10000"
	$(DO) setup VALUE="1.2.3-betatest.99999" execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.100000"
	$(DO) setup VALUE="1.2.3-betatest.100000" execute ACTION="version.nextcyclestep" verify EXPECTED="1.2.3-betatest.100001"

	$(DO) header TEXT="version.nextcyclestep is idempotent when cycle name is not defined"
	$(DO) setup VALUE="" execute ACTION="version.nextcyclestep" verify EXPECTED="0.0.0"
	$(DO) setup VALUE="3.14.15" execute ACTION="version.nextcyclestep" verify EXPECTED="3.14.15"
